#!/usr/bin/env python
#
#  Copyright (c) 2011-2012, Sean Reifschneider, tummy.com, ltd.
#  All Rights Reserved.
#
#  Create the test database
#
#  Probably run with these commands:
#  WARNING: Will destroy your existing database
#
#    dropdb networkattachedbackup
#    createdb -O networkattachedbackup networkattachedbackup
#    python tools/createtestdb -v

#  Look in current and parent directory for model
import sys
sys.path.append('./lib')
sys.path.append('../lib')

import os
import datetime
from nabdb import *

db = nabdb.connect(path_list=[os.path.expanduser(
        '~/.networkattachedbackup-dbcredentials')], echo='-v' in sys.argv)
nabdb.Base.metadata.create_all()

metadata = Metadata()
db.add(metadata)
db.commit()

server = BackupServer()
server.hostname = 'localhost'
db.add(server)

fs_storage = Storage()
fs_storage.backup_server = server
fs_storage.method = 'fs'
fs_storage.arg1 = '/tmp/backups'
db.add(fs_storage)

client1 = Host()
client1.backup_server = server
client1.hostname = 'localhost'
client1.window_start = datetime.time(0, 0)
client1.window_end = datetime.time(5, 0)
db.add(client1)

config_default = HostConfig()
config_default.alerts_mail_address = 'root'
config_default.failure_warn_after = datetime.timedelta(days=3)
config_default.use_global_filters = True
db.add(config_default)

for path in ['/tmp/', '/var/log/', '/home/*/.mozilla/*/*/Cache', '/var/log/',
       '/dev/', '/proc/', '/sys/']:
    filter_global = FilterRule()
    filter_global.rsync_rule = 'exclude %s' % path
    db.add(filter_global)

filter1_client1 = FilterRule()
filter1_client1.host = client1
filter1_client1.rsync_rule = 'exclude /home/*/data/'
filter1_client1.priority = 0.4
db.add(filter1_client1)

db.commit()
